config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end
  root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find([params[:id]])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')

  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">

  <div class="comment_content">
    <p class="comment_name"><strong> <%= comment.name %></strong></p>
    <p class="comment body"><%= comment.body%></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>
  <% if @post.user == current_user  %>
    <p>
      <%= link_to 'delete', [comment.post, comment], method: :delete,
      class: "button",
          data: {confirm: "Are you sure?"}%>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%=  form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body%>
  </p>

  <p>
    <%= f.submit%>
  </p>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag "mylogo.png"%>
        <% end %>

      </div>

      <ul>
        <li class="category">Web site</li>
        <li><%= link_to "Blog", root_path%></li>
      </ul>
      <ul>
        <li class="category">Social</li>
        <li><a href="http://www.realm00.com">realm</a></li>
        <li><a href="https://github.com/takukawasaki">github</a></li>
      </ul>


      <% if user_signed_in? %>
        <p class="sign_in">
          Admin login
        </p>
      <% else %>
        <ul>
          <li><%= link_to 'Sign up', new_user_registration_path%></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        </ul>
      <% end %>
    </div>

    <div id="main_content">
      <div id="header">
        <p>All post</p>

        <% if user_signed_in? %>
          <div class="buttons">
            <%= button_to "new post", new_post_path, :method => 'get' %>
            <%= button_to "log out", destroy_user_session_path, method: :delete %>
          </div>
        <% end %>

      </div>

      <% flash.each do |name, msg|  %>
        <%= content_tag(:div, msg, class: "alert")%>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|  %>
  <% if @post.errors.any?  %>
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
  <% end %>
  <ul>
    <% @post.errors.full_messages.each do |msg|  %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_field :body%>
  </p>

  <p>
    <%= f.submit%>

  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrappeer">
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title">
      <%= link_to post.title, post %>
    </h2>
    <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrappeer">
  <h1>New Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %>Ago
    <% if @post.user == current_user %>
      | <%= link_to "edit", edit_post_path(@post) %>
      | <%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}%>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count%> comments</h2>
    <%= render @post.comments%>
    <h3>Add comment</h3>
    <%= render 'comments/form' %>
  </div>
</div>